### ISSUE TITLE
Allow Binders to replace widget in UIFile

### ISSUE THREAD

**Issue by rkern** [enthought/qt_binder#23]
Right now, the only customization you can do is to override which `Binder` that `UIFile` wraps around each widget. The instantiation of the widget is still driven by the underlying toolkit's `.ui` loader. However, we would like to be able to have Designer lay out a widget, but let the user's specified `Binder` take control of instantiating the widget. For example, let's say I have a `Binder` for an Enable `Component`. I might want to open Designer to lay out my form and put a plain `QWidget` as a placeholder for where I want the `Component` to go.

There are two possible implementation approaches. The cheap one is to have the user use a `QWidget` in Designer, then `UIFile` will use that widget as the parent for the widget created by the `Binder`. The user will probably have to be careful with issues like margins and padding. Additionally, the object hierarchy will have an additional widget interposed that users will have to accommodate when specifying stylesheets and the like.

The annoying option is to hook into the `.ui` loader classes to have them ask the `Binder` to instantiate the widget instead of loading `QWidget`. PySide and PyQt4 have substantially different mechanisms for this, and much of the PyQt4 API is technically private.

API-wise, I suggest a new `Dict(Str, Instance(Binder))` trait on `UIFile` in addition to `overrides`. What one calls it might depend on which way we implement it.

**Comment by rkern** [comment]
@pberkes I'm leaning towards the cheap option.

**Comment by pberkes** [comment]
+1 for the cheap option
