### ISSUE TITLE
`UIFile` confused by multiple Binders with same `qclass`

### ISSUE THREAD

**Issue by pberkes** [enthought/qt_binder#30]
For example, `QWidget` maps to `qt_binder.raw_widgets.WithLayout`, which breaks UIFile .

**Comment by pberkes** [comment]
Ah no wrong, the type registry keeps a list with all the mappings. It is UIFile that gets confused, as it takes the last entry in the type registry:
`binder = binder_registry.lookup(obj)()`, which does `self.lookup_all_by_type(typ)[-1]`.
Would it make more sense to return the _first_ element of the list instead?

Title changed.

**Comment by rkern** [comment]
Well, it's arbitrary which one is first, so no. I am just going to exclude those few classes that shouldn't be included in that mapping.
