### ISSUE TITLE
`TraitsUI` does not display label

### ISSUE THREAD

**Issue by pberkes** [enthought/qt_binder#43]
The `TraitsUI` binder does not display the label that the TraitsUI editor usually have.

For example:

```
from qt_binder.api import Bound, TraitsUI
from traits.api import HasStrictTraits, Int
from traitsui.api import Item, View


class NumberView(HasStrictTraits):

    number = Int

    def default_traits_view(self):
        traits_view = View(
            Bound(
                TraitsUI(
                    Item('number', label='A nice little number'),
                ),
            ),
        )
        return traits_view


if __name__ == '__main__':
    dialog = NumberView()
    dialog.configure_traits()
```

Produces

![screen shot 2016-02-26 at 16 09 50](https://cloud.githubusercontent.com/assets/314633/13357683/6398d31e-dca3-11e5-9a55-12a40a6c86c5.png)

**Comment by rkern** [comment]
Intentionally. The `label=...` goes on the `Bound` in order to be laid out correctly.

**Comment by rkern** [comment]
Use a `Form` layout inside the `Bound()` if you want labels.

**Comment by pberkes** [comment]
Ok thanks closing
